name: SoulJars
version: ${project.version}
author: TheBusyBiscuit
description: 黏液科技附加「靈魂儲存罐」繁體中文版。
website: https://github.com/TheBusyBiscuit/souljars

api-version: 1.14
main: io.github.thebusybiscuit.souljars.SoulJars

depend:
- Slimefun
